name: tv
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  flutter_launcher_icons: ^0.9.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  device_preview: ^1.1.0
  easy_autocomplete: ^1.5.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  flutter_onboarding_slider: ^1.0.7
  flutter_spinkit: ^5.1.0
  flutter_styled_toast: ^2.1.3
  we_slide: ^2.3.0
  flutter_sliding_up_panel: ^2.0.1
  dropdown_button2: ^1.6.2
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  expandable_fab_menu: ^0.0.1
  kumi_popup_window: ^2.0.1
  firebase_auth: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: any
  freezed: ^2.0.3+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/im_logo.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

